// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_one_hundred_billion_points = "CgkI0Or-vL0UEAIQBw"; // <GPGSID>
        public const string achievement_man_down = "CgkI0Or-vL0UEAIQBA"; // <GPGSID>
        public const string achievement_its_not_the_future_yet = "CgkI0Or-vL0UEAIQAw"; // <GPGSID>
        public const string achievement_its_over_9000 = "CgkI0Or-vL0UEAIQBQ"; // <GPGSID>
        public const string achievement_one_million_points = "CgkI0Or-vL0UEAIQBg"; // <GPGSID>
        public const string leaderboard_sentury_leaderboard = "CgkI0Or-vL0UEAIQAQ"; // <GPGSID>
        public const string achievement_youre_not_too_heavy_for_me = "CgkI0Or-vL0UEAIQAg"; // <GPGSID>

}

